# Generated by Django 4.2.2 on 2023-06-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=200)),
                ('website_url', models.URLField()),
                ('website_account_name', models.CharField(max_length=200)),
                ('website_password', models.CharField(max_length=200)),
            ],
        ),
    ]
